[package]
name = "cw4"
version = "0.13.4"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "CosmWasm-4 Interface: Groups Members"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"

[dependencies]
cw-storage-plus = { path = "../storage-plus", version = "0.13.4" }
secret-cosmwasm-std = "1.0.0"
schemars = "0.8.11"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }
