[package]
name = "cw2"
version = "0.13.4"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Definition and types for the CosmWasm-2 interface"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"

[dependencies]
secret-cosmwasm-std = "1.0.0"
cw-storage-plus = { path = "../../packages/storage-plus", version = "0.13.4" }
schemars = "0.8.11"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
