[package]
name = "cw-storage-plus"
version = "0.13.4"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Enhanced storage engines"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"

# [features]
# default = ["iterator"]
# iterator = ["cosmwasm-std/iterator"]

[lib]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[dependencies]
secret-cosmwasm-std = "1.0.0"
secret-cosmwasm-storage = "1.0.0"
schemars = "0.8.11"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
secret-toolkit = { version = "0.7.0", default-features = false, features = ["utils", "storage", "serialization"]}

[dev-dependencies]
criterion = { version = "0.3", features = [ "html_reports" ] }
rand = "0.8"

[[bench]]
name = "main"
harness = false
